### ISSUE TITLE
Race condition in the rptest benchmark

### ISSUE THREAD

**Issue by jvoisin** [daanx/mimalloc-bench#70]
Running [isoalloc](https://github.com/struct/isoalloc) with the rptest benchmark resulted in a reproducible [segfault]( https://github.com/struct/isoalloc/issues/57 ), hinting at a race condition in rptest, as [found]( https://github.com/struct/isoalloc/issues/57#issuecomment-983263980 ) by @struct, due to the usage of `sleep` as a synchronisation primitive:

```C
root@67dbecee929b:/# clang -o rptest *.c -lpthread -I. -ggdb -fsanitize=thread
root@67dbecee929b:/# ./rptest 2 0 1 2 500 1000 100 8 16000
crt          2 threads random linear size [8,16000] 500 loops 1000 allocs 100 ops: ==================
WARNING: ThreadSanitizer: data race (pid=17173)
  Write of size 4 at 0x000000fec030 by main thread:
    #0 benchmark_run /code/jmmb/mimalloc-bench/bench/rptest/rptest.c:777:19 (rptest+0x4b51b4)
    #1 main /code/jmmb/mimalloc-bench/bench/rptest/rptest.c:901:9 (rptest+0x4b7ba8)

  Previous read of size 4 at 0x000000fec030 by thread T1:
    #0 benchmark_worker /code/jmmb/mimalloc-bench/bench/rptest/rptest.c:355:10 (rptest+0x4b5a34)
    #1 thread_entry /code/jmmb/mimalloc-bench/bench/rptest/thread.c:29:2 (rptest+0x4b7fc4)

  As if synchronized via sleep:
    #0 nanosleep <null> (rptest+0x4215d8)
    #1 thread_sleep /code/jmmb/mimalloc-bench/bench/rptest/thread.c:78:2 (rptest+0x4b80f4)
    #2 benchmark_run /code/jmmb/mimalloc-bench/bench/rptest/rptest.c:775:3 (rptest+0x4b51a0)
    #3 main /code/jmmb/mimalloc-bench/bench/rptest/rptest.c:901:9 (rptest+0x4b7ba8)

  Location is global 'benchmark_start' of size 4 at 0x000000fec030 (rptest+0x000000fec030)

  Thread T1 (tid=17175, running) created by main thread at:
    #0 pthread_create <null> (rptest+0x4241b4)
    #1 thread_run /code/jmmb/mimalloc-bench/bench/rptest/thread.c:41:12 (rptest+0x4b7f14)
    #2 benchmark_run /code/jmmb/mimalloc-bench/bench/rptest/rptest.c:772:29 (rptest+0x4b5128)
    #3 main /code/jmmb/mimalloc-bench/bench/rptest/rptest.c:901:9 (rptest+0x4b7ba8)

SUMMARY: ThreadSanitizer: data race /code/jmmb/mimalloc-bench/bench/rptest/rptest.c:777:19 in benchmark_run
==================
==================
WARNING: ThreadSanitizer: data race (pid=17173)
  Read of size 8 at 0xfffff5503f68 by thread T1:
    #0 atomic_load_ptr /code/jmmb/mimalloc-bench/bench/rptest/./atomic.h:23:14 (rptest+0x4b7e10)
    #1 put_cross_thread_memory /code/jmmb/mimalloc-bench/bench/rptest/rptest.c:312:10 (rptest+0x4b7d14)
    #2 benchmark_worker /code/jmmb/mimalloc-bench/bench/rptest/rptest.c:469:5 (rptest+0x4b6d1c)
    #3 thread_entry /code/jmmb/mimalloc-bench/bench/rptest/thread.c:29:2 (rptest+0x4b7fc4)

  Previous write of size 8 at 0xfffff5503f68 by main thread:
    #0 atomic_store_ptr /code/jmmb/mimalloc-bench/bench/rptest/./atomic.h:28:17 (rptest+0x4b79d4)
    #1 benchmark_run /code/jmmb/mimalloc-bench/bench/rptest/rptest.c:767:4 (rptest+0x4b4ff4)
    #2 main /code/jmmb/mimalloc-bench/bench/rptest/rptest.c:901:9 (rptest+0x4b7ba8)

  As if synchronized via sleep:
    #0 nanosleep <null> (rptest+0x4215d8)
    #1 thread_sleep /code/jmmb/mimalloc-bench/bench/rptest/thread.c:78:2 (rptest+0x4b80f4)
    #2 benchmark_worker /code/jmmb/mimalloc-bench/bench/rptest/rptest.c:356:3 (rptest+0x4b5a4c)
    #3 thread_entry /code/jmmb/mimalloc-bench/bench/rptest/thread.c:29:2 (rptest+0x4b7fc4)

  Location is heap block of size 272 at 0xfffff5503e80 allocated by main thread:
    #0 calloc <null> (rptest+0x4228b4)
    #1 benchmark_malloc /code/jmmb/mimalloc-bench/bench/rptest/./benchmark.h:41:13 (rptest+0x4b3c5c)
    #2 benchmark_run /code/jmmb/mimalloc-bench/bench/rptest/rptest.c:723:8 (rptest+0x4b49a8)
    #3 main /code/jmmb/mimalloc-bench/bench/rptest/rptest.c:901:9 (rptest+0x4b7ba8)

  Thread T1 (tid=17175, running) created by main thread at:
    #0 pthread_create <null> (rptest+0x4241b4)
    #1 thread_run /code/jmmb/mimalloc-bench/bench/rptest/thread.c:41:12 (rptest+0x4b7f14)
    #2 benchmark_run /code/jmmb/mimalloc-bench/bench/rptest/rptest.c:772:29 (rptest+0x4b5128)
    #3 main /code/jmmb/mimalloc-bench/bench/rptest/rptest.c:901:9 (rptest+0x4b7ba8)

SUMMARY: ThreadSanitizer: data race /code/jmmb/mimalloc-bench/bench/rptest/./atomic.h:23:14 in atomic_load_ptr
==================
==================
WARNING: ThreadSanitizer: data race (pid=17173)
  Atomic write of size 8 at 0xfffff5503ee0 by thread T2:
    #0 __tsan_atomic64_compare_exchange_val <null> (rptest+0x4790d4)
    #1 atomic_cas_ptr /code/jmmb/mimalloc-bench/bench/rptest/./atomic.h:77:9 (rptest+0x4b7e8c)
    #2 put_cross_thread_memory /code/jmmb/mimalloc-bench/bench/rptest/rptest.c:315:12 (rptest+0x4b7d7c)
    #3 benchmark_worker /code/jmmb/mimalloc-bench/bench/rptest/rptest.c:469:5 (rptest+0x4b6d1c)
    #4 thread_entry /code/jmmb/mimalloc-bench/bench/rptest/thread.c:29:2 (rptest+0x4b7fc4)

  Previous read of size 8 at 0xfffff5503ee0 by thread T1:
    #0 atomic_load_ptr /code/jmmb/mimalloc-bench/bench/rptest/./atomic.h:23:14 (rptest+0x4b7e10)
    #1 get_cross_thread_memory /code/jmmb/mimalloc-bench/bench/rptest/rptest.c:323:10 (rptest+0x4b7c50)
    #2 benchmark_worker /code/jmmb/mimalloc-bench/bench/rptest/rptest.c:368:14 (rptest+0x4b5b88)
    #3 thread_entry /code/jmmb/mimalloc-bench/bench/rptest/thread.c:29:2 (rptest+0x4b7fc4)

  Location is heap block of size 272 at 0xfffff5503e80 allocated by main thread:
    #0 calloc <null> (rptest+0x4228b4)
    #1 benchmark_malloc /code/jmmb/mimalloc-bench/bench/rptest/./benchmark.h:41:13 (rptest+0x4b3c5c)
    #2 benchmark_run /code/jmmb/mimalloc-bench/bench/rptest/rptest.c:723:8 (rptest+0x4b49a8)
    #3 main /code/jmmb/mimalloc-bench/bench/rptest/rptest.c:901:9 (rptest+0x4b7ba8)

  Thread T2 (tid=17176, running) created by main thread at:
    #0 pthread_create <null> (rptest+0x4241b4)
    #1 thread_run /code/jmmb/mimalloc-bench/bench/rptest/thread.c:41:12 (rptest+0x4b7f14)
    #2 benchmark_run /code/jmmb/mimalloc-bench/bench/rptest/rptest.c:772:29 (rptest+0x4b5128)
    #3 main /code/jmmb/mimalloc-bench/bench/rptest/rptest.c:901:9 (rptest+0x4b7ba8)

  Thread T1 (tid=17175, running) created by main thread at:
    #0 pthread_create <null> (rptest+0x4241b4)
    #1 thread_run /code/jmmb/mimalloc-bench/bench/rptest/thread.c:41:12 (rptest+0x4b7f14)
    #2 benchmark_run /code/jmmb/mimalloc-bench/bench/rptest/rptest.c:772:29 (rptest+0x4b5128)
    #3 main /code/jmmb/mimalloc-bench/bench/rptest/rptest.c:901:9 (rptest+0x4b7ba8)

SUMMARY: ThreadSanitizer: data race (/code/jmmb/mimalloc-bench/bench/rptest/rptest+0x4790d4) in __tsan_atomic64_compare_exchange_val
==================
==================
WARNING: ThreadSanitizer: data race (pid=17173)
  Read of size 4 at 0x000000fec034 by thread T2:
    #0 atomic_load32 /code/jmmb/mimalloc-bench/bench/rptest/./atomic.h:38:14 (rptest+0x4b7a20)
    #1 benchmark_worker /code/jmmb/mimalloc-bench/bench/rptest/rptest.c:473:8 (rptest+0x4b6d3c)
    #2 thread_entry /code/jmmb/mimalloc-bench/bench/rptest/thread.c:29:2 (rptest+0x4b7fc4)

  Previous atomic write of size 4 at 0x000000fec034 by thread T1:
    #0 __tsan_atomic32_fetch_add <null> (rptest+0x4735a0)
    #1 atomic_incr32 /code/jmmb/mimalloc-bench/bench/rptest/./atomic.h:52:9 (rptest+0x4b7dc4)
    #2 benchmark_worker /code/jmmb/mimalloc-bench/bench/rptest/rptest.c:511:3 (rptest+0x4b6d9c)
    #3 thread_entry /code/jmmb/mimalloc-bench/bench/rptest/thread.c:29:2 (rptest+0x4b7fc4)

  Location is global 'benchmark_threads_sync' of size 4 at 0x000000fec034 (rptest+0x000000fec034)

  Thread T2 (tid=17176, running) created by main thread at:
    #0 pthread_create <null> (rptest+0x4241b4)
    #1 thread_run /code/jmmb/mimalloc-bench/bench/rptest/thread.c:41:12 (rptest+0x4b7f14)
    #2 benchmark_run /code/jmmb/mimalloc-bench/bench/rptest/rptest.c:772:29 (rptest+0x4b5128)
    #3 main /code/jmmb/mimalloc-bench/bench/rptest/rptest.c:901:9 (rptest+0x4b7ba8)

  Thread T1 (tid=17175, running) created by main thread at:
    #0 pthread_create <null> (rptest+0x4241b4)
    #1 thread_run /code/jmmb/mimalloc-bench/bench/rptest/thread.c:41:12 (rptest+0x4b7f14)
    #2 benchmark_run /code/jmmb/mimalloc-bench/bench/rptest/rptest.c:772:29 (rptest+0x4b5128)
    #3 main /code/jmmb/mimalloc-bench/bench/rptest/rptest.c:901:9 (rptest+0x4b7ba8)

SUMMARY: ThreadSanitizer: data race /code/jmmb/mimalloc-bench/bench/rptest/./atomic.h:38:14 in atomic_load32
==================
==================
WARNING: ThreadSanitizer: data race (pid=17173)
  Read of size 4 at 0xfffff5503ee8 by main thread:
    #0 atomic_load32 /code/jmmb/mimalloc-bench/bench/rptest/./atomic.h:38:14 (rptest+0x4b7a20)
    #1 benchmark_run /code/jmmb/mimalloc-bench/bench/rptest/rptest.c:789:38 (rptest+0x4b5258)
    #2 main /code/jmmb/mimalloc-bench/bench/rptest/rptest.c:901:9 (rptest+0x4b7ba8)

  Previous atomic write of size 4 at 0xfffff5503ee8 by thread T2:
    #0 __tsan_atomic32_fetch_add <null> (rptest+0x4735a0)
    #1 atomic_add32 /code/jmmb/mimalloc-bench/bench/rptest/./atomic.h:62:9 (rptest+0x4b7c04)
    #2 benchmark_worker /code/jmmb/mimalloc-bench/bench/rptest/rptest.c:398:5 (rptest+0x4b601c)
    #3 thread_entry /code/jmmb/mimalloc-bench/bench/rptest/thread.c:29:2 (rptest+0x4b7fc4)

  As if synchronized via sleep:
    #0 nanosleep <null> (rptest+0x4215d8)
    #1 thread_sleep /code/jmmb/mimalloc-bench/bench/rptest/thread.c:78:2 (rptest+0x4b80f4)
    #2 benchmark_run /code/jmmb/mimalloc-bench/bench/rptest/rptest.c:784:3 (rptest+0x4b51fc)
    #3 main /code/jmmb/mimalloc-bench/bench/rptest/rptest.c:901:9 (rptest+0x4b7ba8)

  Location is heap block of size 272 at 0xfffff5503e80 allocated by main thread:
    #0 calloc <null> (rptest+0x4228b4)
    #1 benchmark_malloc /code/jmmb/mimalloc-bench/bench/rptest/./benchmark.h:41:13 (rptest+0x4b3c5c)
    #2 benchmark_run /code/jmmb/mimalloc-bench/bench/rptest/rptest.c:723:8 (rptest+0x4b49a8)
    #3 main /code/jmmb/mimalloc-bench/bench/rptest/rptest.c:901:9 (rptest+0x4b7ba8)

  Thread T2 (tid=17176, running) created by main thread at:
    #0 pthread_create <null> (rptest+0x4241b4)
    #1 thread_run /code/jmmb/mimalloc-bench/bench/rptest/thread.c:41:12 (rptest+0x4b7f14)
    #2 benchmark_run /code/jmmb/mimalloc-bench/bench/rptest/rptest.c:772:29 (rptest+0x4b5128)
    #3 main /code/jmmb/mimalloc-bench/bench/rptest/rptest.c:901:9 (rptest+0x4b7ba8)

SUMMARY: ThreadSanitizer: data race /code/jmmb/mimalloc-bench/bench/rptest/./atomic.h:38:14 in atomic_load32
==================
==================
WARNING: ThreadSanitizer: data race (pid=17173)
  Read of size 4 at 0xfffff5503f70 by main thread:
    #0 atomic_load32 /code/jmmb/mimalloc-bench/bench/rptest/./atomic.h:38:14 (rptest+0x4b7a20)
    #1 benchmark_run /code/jmmb/mimalloc-bench/bench/rptest/rptest.c:789:38 (rptest+0x4b5258)
    #2 main /code/jmmb/mimalloc-bench/bench/rptest/rptest.c:901:9 (rptest+0x4b7ba8)

  Previous atomic write of size 4 at 0xfffff5503f70 by thread T2:
    #0 __tsan_atomic32_fetch_add <null> (rptest+0x4735a0)
    #1 atomic_add32 /code/jmmb/mimalloc-bench/bench/rptest/./atomic.h:62:9 (rptest+0x4b7c04)
    #2 benchmark_worker /code/jmmb/mimalloc-bench/bench/rptest/rptest.c:460:32 (rptest+0x4b6b54)
    #3 thread_entry /code/jmmb/mimalloc-bench/bench/rptest/thread.c:29:2 (rptest+0x4b7fc4)

  As if synchronized via sleep:
    #0 nanosleep <null> (rptest+0x4215d8)
    #1 thread_sleep /code/jmmb/mimalloc-bench/bench/rptest/thread.c:78:2 (rptest+0x4b80f4)
    #2 benchmark_run /code/jmmb/mimalloc-bench/bench/rptest/rptest.c:784:3 (rptest+0x4b51fc)
    #3 main /code/jmmb/mimalloc-bench/bench/rptest/rptest.c:901:9 (rptest+0x4b7ba8)

  Location is heap block of size 272 at 0xfffff5503e80 allocated by main thread:
    #0 calloc <null> (rptest+0x4228b4)
    #1 benchmark_malloc /code/jmmb/mimalloc-bench/bench/rptest/./benchmark.h:41:13 (rptest+0x4b3c5c)
    #2 benchmark_run /code/jmmb/mimalloc-bench/bench/rptest/rptest.c:723:8 (rptest+0x4b49a8)
    #3 main /code/jmmb/mimalloc-bench/bench/rptest/rptest.c:901:9 (rptest+0x4b7ba8)

  Thread T2 (tid=17176, running) created by main thread at:
    #0 pthread_create <null> (rptest+0x4241b4)
    #1 thread_run /code/jmmb/mimalloc-bench/bench/rptest/thread.c:41:12 (rptest+0x4b7f14)
    #2 benchmark_run /code/jmmb/mimalloc-bench/bench/rptest/rptest.c:772:29 (rptest+0x4b5128)
    #3 main /code/jmmb/mimalloc-bench/bench/rptest/rptest.c:901:9 (rptest+0x4b7ba8)

SUMMARY: ThreadSanitizer: data race /code/jmmb/mimalloc-bench/bench/rptest/./atomic.h:38:14 in atomic_load32
==================
........756290 memory ops/CPU second (59MiB peak, 3MiB -> 58MiB bytes sample, 1375% overhead)
ThreadSanitizer: reported 6 warnings
```

**Comment by mjp41** [comment]
This benchmark comes from `rpmalloc` you probably should raise the issue there and then we can pull in the fix to mimalloc-bench.  I think it comes from: https://github.com/mjansson/rpmalloc-benchmark (@mjansson)

I'm super interested at how `isoalloc` found the bug?  Was it a large quarantine and turning pages off?

**Comment by jvoisin** [comment]
As said in https://github.com/struct/isoalloc/issues/57, when running mimalloc-bench's [rptest]( https://github.com/daanx/mimalloc-bench/tree/master/bench/rptest ) with isoalloc, a reproducible segfault happens:

```
$ git clone https://github.com/daanx/mimalloc-bench
$ cd mimalloc-bench
$ ./build-bench-env.sh iso bench
$ cd out/bench
$ gdb --args env LD_PRELOAD=/home/jvoisin/dev/mimalloc-bench/extern/iso/build/libisoalloc.so ./rptest 2 0 1 2 500 1000 100 8 16000
gdb-peda$ r
Starting program: /usr/bin/env LD_PRELOAD=/home/jvoisin/dev/mimalloc-bench/extern/iso/build/libisoalloc.so ./rptest 2 0 1 2 500 1000 100 8 16000
process 382334 is executing new program: /home/jvoisin/dev/mimalloc-bench/out/bench/rptest
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
crt          2 threads random linear size [8,16000] 500 loops 1000 allocs 100 ops: [New Thread 0x7ffff7c40640 (LWP 382340)]
[New Thread 0x7ffff743f640 (LWP 382341)]
..
Thread 3 "rptest" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff743f640 (LWP 382341)]
[----------------------------------registers-----------------------------------]
RAX: 0x41572620827d8500 
RBX: 0x31d9374315c0 --> 0x0 
RCX: 0x2 
RDX: 0x2c3 
RSI: 0x400 
RDI: 0x7ffff7fbffd0 --> 0x1 
RBP: 0x0 
RSP: 0x7ffff743ecf0 --> 0x0 
RIP: 0x55555555672c (<benchmark_worker+652>:	mov    rdi,QWORD PTR [rax+rbp*8])
R8 : 0x0 
R9 : 0xb ('\x0b')
R10: 0x1174 
R11: 0x3ffffffffffffff 
R12: 0x2b69f43ee50 --> 0x41572620827d8500 
R13: 0x0 
R14: 0x205470155088 --> 0x2 
R15: 0xfffd65fc
EFLAGS: 0x10206 (carry PARITY adjust zero sign trap INTERRUPT direction overflow)
[-------------------------------------code-------------------------------------]
   0x555555556720 <benchmark_worker+640>:	je     0x555555556792 <benchmark_worker+754>
   0x555555556722 <benchmark_worker+642>:	nop    WORD PTR [rax+rax*1+0x0]
   0x555555556728 <benchmark_worker+648>:	mov    rax,QWORD PTR [r12]
=> 0x55555555672c <benchmark_worker+652>:	mov    rdi,QWORD PTR [rax+rbp*8]
   0x555555556730 <benchmark_worker+656>:	add    rbp,0x1
   0x555555556734 <benchmark_worker+660>:	sub    r13d,DWORD PTR [rdi]
   0x555555556737 <benchmark_worker+663>:	call   0x5555555561f0 <free@plt>
   0x55555555673c <benchmark_worker+668>:	mov    rax,QWORD PTR [r12+0x8]
[------------------------------------stack-------------------------------------]
0000| 0x7ffff743ecf0 --> 0x0 
0008| 0x7ffff743ecf8 --> 0xa0 
0016| 0x7ffff743ed00 --> 0x31d937430000 --> 0x0 
0024| 0x7ffff743ed08 --> 0x51 ('Q')
0032| 0x7ffff743ed10 --> 0x2c3 
0040| 0x7ffff743ed18 --> 0x50 ('P')
0048| 0x7ffff743ed20 --> 0x5b ('[')
0056| 0x7ffff743ed28 --> 0x0 
[------------------------------------------------------------------------------]
Legend: code, data, rodata, value
Stopped reason: SIGSEGV
0x000055555555672c in benchmark_worker ()
gdb-peda$ bt
#0  0x000055555555672c in benchmark_worker ()
#1  0x0000555555558311 in thread_entry ()
#2  0x00007ffff7f86450 in start_thread (arg=0x7ffff743f640) at pthread_create.c:473
#3  0x00007ffff7d5ad53 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
gdb-peda$ 
```

I didn't do any further analysis, and @struct didn't [push his investigations super-far]( https://github.com/struct/isoalloc/issues/57#issuecomment-983788667 ):

> I believe its segfaulting due to a sometimes uninitialized foreign structure. I didn't run it down beyond that. Of course its possible this is due to some behavior in isoalloc but I couldn't pinpoint it. If you see something that points you in that direction please update this issue and I'll run it down!

**Comment by mjansson** [comment]
I don't understand the output of that sanitizer, it says

`Write of size 4 at 0x000000fec030 by main thread:
    #0 benchmark_run /code/jmmb/mimalloc-bench/bench/rptest/rptest.c:777:19 (rptest+0x4b51b4)`

but looking at `rptest.c` in this repo (since it's slightly modified from the source file in my repo) that line is

`while (atomic_load32(&benchmark_threads_sync) < (int32_t)thread_count) {`

which is a read, not a write?

**Comment by jvoisin** [comment]
The interesting part is a bit later I think:

```
  As if synchronized via sleep:
    #0 nanosleep <null> (rptest+0x4215d8)
    #1 thread_sleep /code/jmmb/mimalloc-bench/bench/rptest/thread.c:78:2 (rptest+0x4b80f4)
    #2 benchmark_run /code/jmmb/mimalloc-bench/bench/rptest/rptest.c:775:3 (rptest+0x4b51a0)
    #3 main /code/jmmb/mimalloc-bench/bench/rptest/rptest.c:901:9 (rptest+0x4b7ba8)
    ``

**Comment by mjansson** [comment]
I assume it's referring to the sleep on line 772, not 775? In any case, that's just a poor man's semaphore to get the threads running at roughly the same time and has nothing to do with the foreign pointers, they're handled by a ABA protected CAS in `put_cross_thread_memory` and `get_cross_thread_memory` - basically a linked list of pointers to free in another thread than the thread that allocated it.

**Comment by mjansson** [comment]
Is this on x64 or aarch64 by the way?

**Comment by jvoisin** [comment]
On x64 :)

**Comment by mjansson** [comment]
Sorry, I can't really make any sense of the sanitizer output

`
WARNING: ThreadSanitizer: data race (pid=17173)
  Atomic write of size 8 at 0xfffff5503ee0 by thread T2:
    #0 __tsan_atomic64_compare_exchange_val <null> (rptest+0x4790d4)
    #1 atomic_cas_ptr /code/jmmb/mimalloc-bench/bench/rptest/./atomic.h:77:9 (rptest+0x4b7e8c)
    #2 put_cross_thread_memory /code/jmmb/mimalloc-bench/bench/rptest/rptest.c:315:12 (rptest+0x4b7d7c)
    #3 benchmark_worker /code/jmmb/mimalloc-bench/bench/rptest/rptest.c:469:5 (rptest+0x4b6d1c)
    #4 thread_entry /code/jmmb/mimalloc-bench/bench/rptest/thread.c:29:2 (rptest+0x4b7fc4)

  Previous read of size 8 at 0xfffff5503ee0 by thread T1:
    #0 atomic_load_ptr /code/jmmb/mimalloc-bench/bench/rptest/./atomic.h:23:14 (rptest+0x4b7e10)
    #1 get_cross_thread_memory /code/jmmb/mimalloc-bench/bench/rptest/rptest.c:323:10 (rptest+0x4b7c50)
    #2 benchmark_worker /code/jmmb/mimalloc-bench/bench/rptest/rptest.c:368:14 (rptest+0x4b5b88)
    #3 thread_entry /code/jmmb/mimalloc-bench/bench/rptest/thread.c:29:2 (rptest+0x4b7fc4)
`

The pointers are zero initialized before the threads can start (handled by the "semaphore" style `benchmark_start` - so no thread can read the pointer before it's initialized to 0. And the ABA protection of the CAS based linked list guarantees that a write and read are always safe (multiple producers, single consumer).

**Comment by mjansson** [comment]
So sure, thread T1 benchmark_worker can read the pointer before thread T2 benchmark_worker writes it, but that's fine since it's initialized to 0 by the main thread before any of the worker threads reach that point (ensured by the `benchmark_start` gatekeeper, NOT by the thread sleep)

**Comment by daanx** [comment]
@mjansson thanks for joining the conversation :-) hope we can figure out what is happening -- I have not looked at this yet in detail myself. (I guess it could be a limitation in TSAN or a bug in isoalloc as well?)  Could we perhaps add a stronger barrier after initialization that would make it more apparent to TSAN?

**Comment by mjansson** [comment]
you can try just getting rid of the thread sleep and see what the thread sanitiser says then, it's mostly there to make sure threads launch execution at the same time and remove the thread setup variation from benchmark results

**Comment by mjp41** [comment]
I have modified the benchmark to call C11 atomics, and to make the `benchmark-start` flag atomic.  This has removed the TSan errors when I build and run it.

**Comment by mjp41** [comment]
This doesn't seem to be crashing with isoalloc perhaps something has changed that fixed the underlying issue since this was raised?

**Comment by mjansson** [comment]
Unfortunately Visual Studio still doesn't support C11 atomics, but I'll change upstream the benchmark start flag to an atomic and use <stdatomic.h> on non-MSVC compilers

**Comment by jvoisin** [comment]
@mjansson when it's done, can you please link the relevant commit here, and close this issue?

**Comment by mjansson** [comment]
The upstream benchmark repo has been updated to use stdatomic on gcc/clang and an atomic for the start variable - https://github.com/mjansson/rpmalloc-benchmark/commit/65f9ae0475ba02fcf29e0525d8a3930b084a24e0

**Comment by mjansson** [comment]
I guess this can be closed now?

**Comment by jvoisin** [comment]
Not before our [internal copy of rptest]( https://github.com/daanx/mimalloc-bench/tree/master/bench/rptest ) is bumped. You might be interested in upstreaming our changes by the way @mjansson :)

**Comment by mjansson** [comment]
Which changes would that be? I was looking at the history @ https://github.com/daanx/mimalloc-bench/commits/master/bench/rptest but didn't see anything significant

**Comment by mjansson** [comment]
If you could make a PR to https://github.com/mjansson/rpmalloc-benchmark I'd be happy to add it
